[package]
name = "monkey"
version = "0.1.0"
authors = ["nathanyee <hooticambo@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "monkey"
doctest = false
test = false

[dependencies]
wasm-bindgen = "0.2.63"
